import { Card, CardContent } from "@/components/ui/card";
import { SectionTitle } from "@/components/shared/Primitives";
import { FirewallChipBadge } from "@/components/shared/FirewallChip";
import { Sparkles, ShieldCheck, ArrowRight } from "lucide-react";
import { aggregateFirewallChips } from "@/lib/firewallChips";
import type { PipelineResult } from "@/lib/types";

export function ConstraintFirewallSection({ pipeline }: { pipeline: PipelineResult | null }) {
  const chips = aggregateFirewallChips(pipeline);

  return (
    <section aria-labelledby="firewall-heading">
      <SectionTitle
        eyebrow="The recurring rule"
        title={<span id="firewall-heading">The LLM proposes. Deterministic code decides.</span>}
        sub="Every vendor recommendation is generated by a language model. Every authorisation decision is made by plain, auditable code that never reads LLM output as an instruction."
      />

      <div className="grid md:grid-cols-2 gap-4 mb-5">
        <Card className="border-line/80">
          <CardContent className="flex flex-col gap-3">
            <div className="flex items-center gap-2 text-gold-hi">
              <Sparkles className="h-4 w-4" aria-hidden="true" />
              <span className="font-mono text-[11px] uppercase tracking-[0.15em]">
                LLM layer — proposes
              </span>
            </div>
            <ul className="text-sm text-text-mid space-y-1.5 list-disc list-inside marker:text-text-dim">
              <li>Parses natural-language briefs into draft constraints</li>
              <li>Ranks vendors with plain-language reasoning</li>
              <li>Writes counterfactual "what-if" explanations</li>
              <li>Never sets AUTHORISED, ESCALATE, or REJECT</li>
            </ul>
          </CardContent>
        </Card>

        <Card className="border-sage/30 bg-sage/[0.04]">
          <CardContent className="flex flex-col gap-3">
            <div className="flex items-center gap-2 text-sage-hi">
              <ShieldCheck className="h-4 w-4" aria-hidden="true" />
              <span className="font-mono text-[11px] uppercase tracking-[0.15em]">
                Code layer — decides
              </span>
            </div>
            <ul className="text-sm text-text-mid space-y-1.5 list-disc list-inside marker:text-text-dim">
              <li>Validates price against the shared budget pool</li>
              <li>Validates quantity, specification, and delivery SLA</li>
              <li>Validates warranty and vendor GSTIN trust</li>
              <li>Sets AUTHORISED, ESCALATE, or REJECT — deterministically</li>
            </ul>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardContent>
          <div className="flex items-center gap-2 text-xs text-text-dim mb-3 font-mono uppercase tracking-wide">
            <span>This run's hard-constraint results</span>
            <ArrowRight className="h-3 w-3" aria-hidden="true" />
          </div>
          {chips.length === 0 ? (
            <p className="text-sm text-text-dim">Run the pipeline to see live firewall results.</p>
          ) : (
            <ul className="flex flex-wrap gap-2" aria-label="Deterministic constraint checks, this run">
              {chips.map((chip) => (
                <li key={chip.label}>
                  <FirewallChipBadge chip={chip} />
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </section>
  );
}
